# This file should be pushed to danielflook/python-minifier-build:fedora30-<date>
FROM fedora:30

# CircleCI required tools
RUN dnf install -y \
      git \
      openssh \
      tar \
      gzip \
      gpg \
      ca-certificates \
 && dnf update -y

# Python versions
RUN dnf install -y \
      python26 \
      python27 \
      python34 \
      python35 \
      python36 \
      python37 \
      python38 \
      pypy \
      pypy3 \
      python2-test \
      python3-test

WORKDIR /tmp/work
ENTRYPOINT ["/bin/bash"]
