# This file should be pushed to danielflook/python-minifier-build:fedora28-<date>
FROM fedora:28

# CircleCI required tools
RUN dnf install -y \
      git \
      openssh \
      tar \
      gzip \
      gpg \
      ca-certificates \
  && dnf clean all && rm -rf /var/cache/dnf/*

# Python versions
RUN dnf install -y \
      python33 \
  && dnf clean all && rm -rf /var/cache/dnf/*

# Other packages required for tests
RUN dnf install -y \
      bzip2 \
  && dnf clean all && rm -rf /var/cache/dnf/*

WORKDIR /tmp/work
ENTRYPOINT ["/bin/bash"]
