# This file should be pushed to danielflook/python-minifier-build:fedora30-<date>
FROM fedora:30

# CircleCI required tools
RUN dnf install -y \
      git \
      openssh \
      tar \
      gzip \
      gpg \
      ca-certificates \
  && dnf clean all && rm -rf /var/cache/dnf/*

# Python versions
RUN dnf install -y \
      python26 \
      python27 \
      python34 \
      python35 \
      python36 \
      python37 \
      python38 \
      pypy \
      pypy3 \
      python2-test \
      python3-test \
  && dnf clean all && rm -rf /var/cache/dnf/*

# Other packages required for tests
RUN dnf install -y \
      bzip2 \
  && dnf clean all && rm -rf /var/cache/dnf/*

WORKDIR /tmp/work
ENTRYPOINT ["/bin/bash"]
