FROM danielflook/python-minifier-build:python3.15-2026-09-10 AS fuzz

RUN pip3 install --no-cache-dir --root-user-action=ignore 'hypothesis[cli]' hypofuzz

COPY fuzz.sh /fuzz.sh
ENTRYPOINT ["/fuzz.sh"]

EXPOSE 9999/tcp
VOLUME /tmp/work
