FROM fedora:42 AS python3.14

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# CircleCI required tools
RUN <<EOF
    dnf install -y \
        git \
        tar \
        gzip \
        gpg \
        ca-certificates
    dnf clean all && rm -rf /var/cache/dnf/*
EOF

# Development tools
RUN <<EOF
    dnf install -y \
        @development-tools \
        findutils \
        zlib-devel \
        bzip2-devel \
        ncurses-devel \
        gdbm-devel \
        openssl-devel \
        sqlite-devel \
        tk-devel \
        libuuid-devel \
        readline-devel \
        libnsl2-devel \
        xz-devel \
        libffi-devel \
        wget
    git clone https://github.com/python/cpython.git
    cd cpython
    git checkout v3.14.0rc2
    ./configure
    make
    make install
    cd ..
    rm -rf cpython
    dnf clean all && rm -rf /var/cache/dnf/*
EOF

# Other packages required for tests
RUN <<EOF
    dnf install -y bzip2
    dnf clean all && rm -rf /var/cache/dnf/*
EOF

RUN pip3 install --no-cache-dir tox==4.28.4 virtualenv==20.34.0 cachetools==6.1.0 chardet==5.2.0 colorama==0.4.6 distlib==0.4.0 filelock==3.19.1 packaging==25.0 platformdirs==4.3.8 pluggy==1.6.0 pyproject-api==1.9.1

WORKDIR /tmp/work
ENTRYPOINT ["/bin/bash"]
