FROM fedora:34 AS python3.10

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# CircleCI required tools
RUN <<EOF
    dnf install -y \
        git \
        openssh \
        tar \
        gzip \
        gpg \
        ca-certificates
    dnf clean all && rm -rf /var/cache/dnf/*
EOF

# Development tools
RUN <<EOF
    dnf install -y \
        @development-tools \
        findutils \
        zlib-devel \
        bzip2-devel \
        ncurses-devel \
        gdbm-devel \
        openssl-devel \
        sqlite-devel \
        tk-devel \
        libuuid-devel \
        readline-devel \
        libnsl2-devel \
        xz-devel \
        libffi-devel \
        wget
    git clone https://github.com/python/cpython.git
    cd cpython
    git checkout v3.10.0
    ./configure
    make
    make install
    cd ..
    rm -rf cpython
    dnf clean all && rm -rf /var/cache/dnf/*
EOF

# Other packages required for tests
RUN <<EOF
    dnf install -y bzip2
    dnf clean all && rm -rf /var/cache/dnf/*
EOF

RUN pip3 install --no-cache-dir tox==3.24.1 virtualenv==20.26.4 distlib==0.4.0 filelock==3.19.1 packaging==25.0 platformdirs==4.3.8 pluggy==1.6.0 py==1.11.0 six==1.17.0 toml==0.10.2

WORKDIR /tmp/work
ENTRYPOINT ["/bin/bash"]
