FROM fedora:30 AS base

# CircleCI required tools
RUN <<EOF
    dnf install -y \
        git \
        openssh \
        tar \
        gzip \
        gpg \
        ca-certificates
    dnf clean all && rm -rf /var/cache/dnf/*
EOF

# Other packages required for tests
RUN <<EOF
    dnf install -y bzip2
    dnf clean all && rm -rf /var/cache/dnf/*
EOF

RUN pip3 install --no-cache-dir tox==3.11.1 virtualenv==16.6.0 filelock==3.12.2 importlib-metadata==6.7.0 pluggy==0.13.1 py==1.11.0 six==1.17.0 toml==0.10.2 typing-extensions==4.7.1 zipp==3.15.0

WORKDIR /tmp/work
ENTRYPOINT ["/bin/bash"]

##
FROM base AS python2.7

RUN <<EOF
    dnf install -y \
        python27 \
        python2-test \
        python2-pip \
        findutils
    dnf clean all && rm -rf /var/cache/dnf/*
EOF

##
FROM base AS python3.4

RUN <<EOF
    dnf install -y python34
    dnf clean all && rm -rf /var/cache/dnf/*
    curl https://bootstrap.pypa.io/pip/3.4/get-pip.py | python3.4
EOF

##
FROM base AS python3.5

RUN <<EOF
    dnf install -y python35
    dnf clean all && rm -rf /var/cache/dnf/*
    curl https://bootstrap.pypa.io/pip/3.5/get-pip.py | python3.5
EOF

##
FROM base AS python3.6

RUN <<EOF
    dnf install -y python36
    dnf clean all && rm -rf /var/cache/dnf/*
    curl https://bootstrap.pypa.io/pip/3.6/get-pip.py | python3.6
EOF

##
FROM base AS python3.7

RUN <<EOF
    dnf install -y \
        python37 \
        python3-test \
        python3-pip
    dnf clean all && rm -rf /var/cache/dnf/*
EOF

##
FROM base AS python3.8

RUN <<EOF
    dnf install -y python38
    dnf clean all && rm -rf /var/cache/dnf/*
    curl https://bootstrap.pypa.io/pip/3.8/get-pip.py | python3.8
EOF

##
FROM base AS pypy

RUN <<EOF
    dnf install -y pypy
    dnf clean all && rm -rf /var/cache/dnf/*
EOF

##
FROM base AS pypy3

RUN <<EOF
    dnf install -y pypy3
    dnf clean all && rm -rf /var/cache/dnf/*
EOF
