FROM fedora:42 AS fuzz

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN <<EOF
    dnf install -y \
        python3 \
        python3-pip
    dnf clean all && rm -rf /var/cache/dnf/*
EOF

RUN pip install --no-cache-dir hypothesis[cli] hypofuzz

COPY fuzz.sh /fuzz.sh

WORKDIR /tmp/work
ENTRYPOINT ["/fuzz.sh"]

EXPOSE 9999/tcp
VOLUME /tmp/work
