FROM fedora:28 AS python3.3

# CircleCI required tools
RUN dnf install -y \
      openssh \
      tar \
      gzip \
      gpg \
      ca-certificates \
  && dnf clean all && rm -rf /var/cache/dnf/*

# Install git
RUN dnf install -y \
    @development-tools \
    dh-autoreconf \
    curl-devel \
    expat-devel \
    gettext-devel \
    openssl-devel \
    perl-devel \
    zlib-devel \
 && dnf clean all && rm -rf /var/cache/dnf/* \
 && curl -f -L https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.18.5.tar.gz --output git-2.18.5.tar.gz \
 && tar -zxf git-2.18.5.tar.gz \
 && cd git-2.18.5 \
 && make configure \
 && ./configure --prefix=/usr/local \
 && make all \
 && make install \
 && cd .. \
 && rm -rf git-2.18.5 \
 && dnf autoremove -y \
    @development-tools \
    dh-autoreconf \
    curl-devel \
    expat-devel \
    gettext-devel \
    openssl-devel \
    perl-devel \
    zlib-devel \
 && dnf clean all && rm -rf /var/cache/dnf/*

# Python versions
RUN dnf install -y \
      python33 \
  && dnf clean all && rm -rf /var/cache/dnf/* \
  && curl https://bootstrap.pypa.io/pip/3.3/get-pip.py | python3.3

# Other packages required for tests
RUN dnf install -y \
      bzip2 \
  && dnf clean all && rm -rf /var/cache/dnf/*

RUN pip3 install 'tox<3' 'virtualenv<16'

WORKDIR /tmp/work
ENTRYPOINT ["/bin/bash"]
